### PR TITLE
Add hotswap pcb variant

### PR DESCRIPTION
**Pull request by luis-godinez**
Changed through-hole mx switch footprints to kaihl hotswap sockets. Re-routed PCB and validated against Design Rules Checker. Same firmware can be used on this version as the pin layout remains the same..

- MX413, the ISO Enter, remains through-hole due to overlapping nets.
- MX515, left 1u shift, was removed due to overlapping nets and inability to route tracks.

PCB Preview: https://imgur.com/a/t7Nzruh

### CODE REVIEW

**Comment by luis-godinez** [comment]
@JellyTitan @dcpedit for review.

**Comment by dcpedit** [comment]
This is amazing work!  Thanks for doing this. I like how you rounded the solder pads to make them fit.  Bummer that same trick won't work for the ISO enter.  I'm assuming you haven't had the PCB manufactured yet.  Maybe it'd be good to put a disclaimer in the README about how it hasn't been tested?

**Comment by luis-godinez** [comment]
Credit to you for doing most of the heavy lifting, the diode layout and pin mapping. I'll add a disclaimer in the README and update the pcb preview. Currently awaiting a small batch of PCBs from the fab but I don't expect any issues after having validated against the Electrical Rules Checker and the Design Rules Checker.

**Comment by luis-godinez** [comment]
@dcpedit ready for your review. I'll update readme disclaimer upon testing the pcbs.

**Pull request merged**
